export const FIRST_ENTER = 'FIRST_ENTER'
export const SESSION_START = 'SESSION_START'
export const LOCK = 'LOCK'
export const LOG_OUT_CACHE = 'LOG_OUT_CACHE'
export const PASSWORD_AFTER_LOG_OUT = 'PASSWORD_AFTER_LOG_OUT'
export const SUCCESS_ENTER = 'SUCCESS_ENTER'

// Onboarding
export const ONBOARDING = 'ONBOARDING'
export const ANALYTICS_OK = 'ANALYTICS_OK'
export const WELCOME = 'WELCOME'
export const START_CREATE = 'START_CREATE'
export const START_PASSWORD = 'START_PASSWORD'
export const START_BACKUP = 'START_BACKUP'
export const START_RESTORE = 'START_RESTORE'
export const START_RESTORE_CONFIRM = 'START_RESTORE_CONFIRM'
export const START_RESTORE_PASSWORD = 'START_RESTORE_PASSWORD'

// Adding address
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const ADD_ADDRESS_GENERATE = 'ADD_ADDRESS_GENERATE'
export const ADD_ADDRESS_GENERATE_BACKUP = 'ADD_ADDRESS_GENERATE_BACKUP'
export const ADD_ADDRESS_IMPORT = 'ADD_ADDRESS_IMPORT'
export const ADD_ADDRESS_CONFIRM = 'ADD_ADDRESS_CONFIRM'
export const ADD_ADDRESS_IMPORT_BACKUP = 'ADD_ADDRESS_IMPORT_BACKUP'

// Send, Receive
export const ADDRESS_SEND = 'ADDRESS_SEND'
export const BALANCE_CHANGED = 'BALANCE_CHANGED'

// Exchange
export const TOUCH_EXCHANGE = 'TOUCH_EXCHANGE'

// Passcode
export const PASSCODE_ENABLED = 'PASSCODE_ENABLED'
export const PASSCODE_DISABLED = 'PASSCODE_DISABLED'
export const PASSCODE_LOCKED_INVALID = 'PASSCODE_LOCKED_INVALID'
export const PASSCODE_LOCKED_FORGOT = 'PASSCODE_LOCKED_FORGOT'

// Other
export const FILTERS_WATCH = 'FILTERS_WATCH'
export const HISTORY_WATCH = 'HISTORY_WATCH'
export const NFT_WATCH = 'NFT_WATCH'
export const ADDRESS_WATCH = 'ADDRESS_WATCH'
export const ADDRESS_ACTION = 'ADDRESS_ACTION'
export const TRANSACTION_AUTO_FILL = 'TRANSACTION_AUTO_FILL'
export const TRANSACTION_START = 'TRANSACTION_START'
export const TRANSACTION_CANCEL = 'TRANSACTION_CANCEL'
export const TRANSACTION_CONFIRM = 'TRANSACTION_CONFIRM'
export const TRANSACTION_PASSWORD = 'TRANSACTION_PASSWORD'

// NPS
export const NPS_GET = 'NPS_GET'
export const NPS_FINISH = 'NPS_FINISH'

// Hardware
export const HARDWARE_CONNECT = 'HARDWARE_CONNECT'

// Settings
export const BACKUP_SETTINGS = 'BACKUP_SETTINGS'
export const SETTINGS_SIGN_IN = 'SETTINGS_SIGN_IN'
export const SETTINGS_NEWTAB = 'SETTINGS_NEWTAB'
