// https://github.com/cosmos/chain-registry

// Types
import { TChain } from './types'

const chains: TChain[] = [
  {
    denom: 'uatom',
    prefix: 'cosmos',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.cosmos.network/',
      'https://rpc-cosmoshub.blockapsis.com',
      'https://cosmos-rpc.quickapi.com:443',
      'https://rpc-cosmoshub.whispernode.com',
      'https://cosmoshub.validator.network/',
    ],
    chain: 'cosmos',
    standingFee: 0.0025,
    gas: '200000',
  },
  {
    denom: 'uakt',
    prefix: 'akash',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.akash.forbole.com:443',
      'https://rpc-akash.ecostake.com:443',
      'https://akash-rpc.polkachu.com',
      'https://rpc-akash-ia.cosmosia.notional.ventures:443',
    ],
    chain: 'akash',
    standingFee: 0.003,
    gas: '120000',
  },
  {
    denom: 'umntl',
    prefix: 'mantle',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.assetmantle.one/',
      'https://rpc-assetmantle.ecostake.com',
      'https://assetmantle-rpc.polkachu.com',
      'https://rpc.asset-mantle.ezstaking.io',
      'https://rpc.assetmantle.nodestake.top',
      'https://rpc-assetmantle-ia.cosmosia.notional.ventures/',
    ],
    chain: 'asset-mantle',
    standingFee: 0.0025,
    gas: '100000',
  },
  {
    denom: 'uband',
    prefix: 'band',
    hdPaths: "m/44'/494'/0'/0/0",
    rpcUrls: [
      'http://rpc.laozi1.bandchain.org:80',
      'https://rpc-bandchain-ia.cosmosia.notional.ventures/',
      'https://band-rpc.ibs.team/',
    ],
    chain: 'band',
    standingFee: 0.0025,
    gas: '100000',
  },
  {
    denom: 'ubcna',
    prefix: 'bcna',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.bitcanna.io',
      'https://rpc.bitcanna.ezstaking.io',
      'https://rpc-bitcanna.itastakers.com/',
      'https://bitcanna-rpc.polkachu.com',
      'https://rpc-bitcanna-ia.cosmosia.notional.ventures/',
      'https://bitcanna-rpc.panthea.eu',
    ],
    chain: 'bitcanna',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'ubtsg',
    prefix: 'bitsong',
    hdPaths: "m/44'/639'/0'/0/0",
    rpcUrls: [
      'https://rpc-bitsong.itastakers.com',
      'https://rpc.bitsong.interbloc.org',
      'https://rpc-bitsong-ia.cosmosia.notional.ventures/',
      'https://rpc.explorebitsong.com',
      'https://bitsong-rpc.validatrium.club',
      'https://bitsong-rpc.panthea.eu',
      'https://rpc.bitsong.chaintools.tech/',
      'https://rpc.bitsong.freak12techno.io/',
    ],
    chain: 'bitsong',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'ucrbrus',
    prefix: 'cerberus',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.cerberus.zone:26657/',
      'https://rpc-cerberus.ecostake.com',
      'https://cerberus-rpc.polkachu.com',
      'https://rpc-cerberus-ia.cosmosia.notional.ventures/',
      'https://cerberus-rpc.panthea.eu',
    ],
    chain: 'cerberus',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'uhuahua',
    prefix: 'chihuahua',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.chihuahua.wtf/',
      'https://rpc-chihuahua.ecostake.com',
      'https://chihuahua-rpc.polkachu.com',
      'https://rpc-chihuahua-ia.cosmosia.notional.ventures/',
    ],
    chain: 'chihuahua',
    standingFee: 0.00288,
    gas: '100000',
  },
  {
    denom: 'ucmdx',
    prefix: 'comdex',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://api.comdex.audit.one/rpc',
      'https://rpc.comdex.one',
      'https://rpc-comdex.zenchainlabs.io/',
      'https://comdex-rpc.polkachu.com',
      'https://rpc.comdex.ezstaking.io',
    ],
    chain: 'comdex',
    standingFee: 0.0024,
    gas: '96000',
  },
  {
    denom: 'basecro',
    prefix: 'cro',
    hdPaths: "m/44'/394'/0'/0/0",
    rpcUrls: [
      'https://mainnet.crypto.org',
      'https://rpc-crypto-org.keplr.app',
      'https://rpc-cryptoorgchain-ia.cosmosia.notional.ventures',
      'https://rpc-cryptoorgchain.ecostake.com',
    ],
    chain: 'crypto-org',
    standingFee: 0.000024,
    gas: '96000',
  },
  {
    denom: 'udsm',
    prefix: 'desmos',
    hdPaths: "m/44'/852'/0'/0/0",
    rpcUrls: [
      'https://rpc.mainnet.desmos.network',
      'https://rpc.desmos.ezstaking.io',
      'https://desmos-rpc.panthea.eu',
    ],
    chain: 'desmos',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'ungm',
    prefix: 'emoney',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc-emoney.keplr.app',
      'https://emoney.validator.network',
      'https://rpc.emoney.badgerbite.xyz:443',
      'https://rpc.emoney.ezstaking.io',
      'https://rpc-emoney-ia.cosmosia.notional.ventures',
      'https://rpc.emoney.freak12techno.io',
    ],
    chain: 'emoney',
    standingFee: 0.08,
    gas: '80000',
  },
  {
    denom: 'aevmos',
    prefix: 'evmos',
    hdPaths: "m/44'/60'/0'/0/0",
    rpcUrls: [
      'https://rpc-evmos.ecostake.com',
      'https://rpc-evmos.whispernode.com',
      'https://tendermint.bd.evmos.org:26657',
      'https://rpc.evmos.ezstaking.io',
      'https://rpc-evmos-ia.cosmosia.notional.ventures:443',
      'https://rpc.evmos.posthuman.digital',
      'https://rpc.evmos.interbloc.org',
      'https://rpc.evmos.testnet.run',
      'https://rpc.evmos.nodestake.top',
      'https://rpc.evmos.bh.rocks',
      'https://rpc-evmos.goldenratiostaking.net',
      'https://rpc.evmos.chaintools.tech',
      'https://evmos-rpc.polkachu.com',
      'https://rpc.evmos.silknodes.io',
    ],
    chain: 'evmos',
    standingFee: 0.0035,
    gas: '140000',
  },
  {
    denom: 'afet',
    prefix: 'fetch',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc-fetchhub.fetch.ai:443',
      'https://fetchapi.terminet.io',
      'https://rpc-fetchhub-ia.cosmosia.notional.ventures',
      'https://fetch-rpc.polkachu.com',
    ],
    chain: 'fetchai',
    standingFee: 0.0006,
    gas: '100000',
  },
  {
    denom: 'ugraviton',
    prefix: 'gravity',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://gravitychain.io:26657',
      'https://gravity-rpc.polkachu.com',
      'https://rpc.gravity-bridge.ezstaking.io',
      'https://rpc-gravitybridge-ia.cosmosia.notional.ventures',
      'https://rpc.gravity-bridge.nodestake.top',
    ],
    chain: 'gravity-bridge',
    standingFee: 0,
    gas: '100000',
  },
  {
    denom: 'uiris',
    prefix: 'iaa',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: ['https://rpc-iris.keplr.app', 'https://rpc-irisnet-ia.cosmosia.notional.ventures'],
    chain: 'iris',
    standingFee: 0.024,
    gas: '90000',
  },
  {
    denom: 'ujuno',
    prefix: 'juno',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc-juno.whispernode.com',
      'https://rpc-juno.itastakers.com',
      'https://rpc-juno.ecostake.com',
      'https://juno-rpc.polkachu.com',
      'https://rpc.juno.pupmos.network',
      'https://rpc.junomint.com',
      'https://rpc-juno-ia.cosmosia.notional.ventures',
      'https://rpc.juno.chaintools.tech',
    ],
    chain: 'juno',
    standingFee: 0.0002,
    gas: '80000',
  },
  {
    denom: 'ukava',
    prefix: 'kava',
    hdPaths: "m/44'/459'/0'/0/0",
    rpcUrls: [
      'https://rpc.kava.io/',
      'https://kava-rpc.polkachu.com',
      'https://rpc-kava-ia.cosmosia.notional.ventures',
    ],
    chain: 'kava',
    standingFee: 0.007,
    gas: '180000',
  },
  {
    denom: 'uxki',
    prefix: 'ki',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc-mainnet.blockchain.ki',
      'https://kichain-rpc.polkachu.com',
      'https://rpc.kichain.ezstaking.io',
      'https://rpc-kichain-ia.cosmosia.notional.ventures',
      'https://rpc.kichain.chaintools.tech',
    ],
    chain: 'ki-chain',
    standingFee: 0.0024,
    gas: '85000',
  },
  {
    denom: 'udarc',
    prefix: 'darc',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://node1.konstellation.tech:26657',
      'https://konstellation-rpc.polkachu.com',
      'https://rpc.konstellation.badgerbite.xyz:443',
      'https://rpc-konstellation-ia.cosmosia.notional.ventures',
    ],
    chain: 'konstellation',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'ulum',
    prefix: 'lum',
    hdPaths: "m/44'/880'/0'/0/0",
    rpcUrls: ['https://node0.mainnet.lum.network/rpc', 'https://node0.mainnet.lum.network/rest'],
    chain: 'lum',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'umed',
    prefix: 'panacea',
    hdPaths: "m/44'/371'/0'/0/0",
    rpcUrls: ['https://rpc.gopanacea.org'],
    chain: 'medibloc',
    standingFee: 0.72,
    gas: '80000',
  },
  {
    denom: 'uosmo',
    prefix: 'osmo',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.osmosis.zone',
      'https://rpc-osmosis.blockapsis.com',
      'https://osmosis-rpc.quickapi.com:443',
      'https://rpc-osmosis.whispernode.com',
      'https://osmosis.validator.network',
      'https://rpc-osmosis.ecostake.com',
      'https://osmosis-rpc.polkachu.com',
      'https://rpc-osmosis-ia.cosmosia.notional.ventures',
      'https://rpc.osmosis.interbloc.org',
    ],
    chain: 'osmosis',
    standingFee: 0.0025,
    gas: '100000',
  },
  {
    denom: 'uxprt',
    prefix: 'persistence',
    hdPaths: "m/44'/750'/0'/0/0",
    rpcUrls: [
      'https://rpc.core.persistence.one',
      'https://rpc-persistent-ia.cosmosia.notional.ventures',
    ],
    chain: 'persistence',
    standingFee: 0.002,
    gas: '80000',
  },
  {
    denom: 'uregen',
    prefix: 'regen',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc-regen.ecostake.com',
      'https://regen.stakesystems.io:2053',
      'https://rpc-regen-ia.cosmosia.notional.ventures',
    ],
    chain: 'regen',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'udvpn',
    prefix: 'sent',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc-sentinel-ia.cosmosia.notional.ventures',
      'https://rpc-sentinel.keplr.app',
      'https://rpc-sentinel.whispernode.com',
      'https://rpc.sentinel1.badgerbite.xyz',
      'https://rpc.sentinel.chaintools.tech',
      'https://rpc.sentinel.freak12techno.io',
    ],
    chain: 'sentinel',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'rowan',
    prefix: 'sif',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.sifchain.finance:443',
      'https://rpc-archive.sifchain.finance:443',
      'https://sifchain.rpc.consensus.one:443',
      'https://sifchain-rpc.polkachu.com',
      'https://rpc-sifchain-ia.cosmosia.notional.ventures',
      'https://rpc-sifchain.ecostake.com',
      'https://rpc.sifchain.chaintools.tech',
    ],
    chain: 'sifchain',
    standingFee: 0.18,
    gas: '120000',
  },
  {
    denom: 'ustars',
    prefix: 'stars',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.stargaze-apis.com',
      'https://rpc.stargaze.pupmos.network',
      'https://rpc.stargaze.ezstaking.io',
      'https://rpc.stars.kingnodes.com',
      'https://stargaze-rpc.polkachu.com',
      'https://rpc-stargaze-ia.cosmosia.notional.ventures',
      'https://stargaze.c29r3.xyz:443/rpc',
    ],
    chain: 'stargaze',
    standingFee: 0.0025,
    gas: '100000',
  },
  {
    denom: 'uiov',
    prefix: 'star',
    hdPaths: "m/44'/234'/0'/0/0",
    rpcUrls: ['https://rpc-iov.keplr.app', 'https://rpc-starname-ia.cosmosia.notional.ventures'],
    chain: 'starname',
    standingFee: 0.0024,
    gas: '100000',
  },
  {
    denom: 'utgd',
    prefix: 'tgrade',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: ['https://rpc.mainnet-1.tgrade.confio.run', 'https://rpc.tgrade.posthuman.digital'],
    chain: 'tgrade',
    standingFee: 0.005,
    gas: '100000',
  },
  {
    denom: 'uumee',
    prefix: 'umee',
    hdPaths: "m/44'/118'/0'/0/0",
    rpcUrls: [
      'https://rpc.aphrodite.main.network.umee.cc',
      'https://rpc.apollo.main.network.umee.cc',
      'https://rpc.artemis.main.network.umee.cc',
      'https://rpc.athena.main.network.umee.cc',
      'https://rpc.beaked.main.network.umee.cc',
      'https://rpc.bottlenose.main.network.umee.cc',
      'https://umee-rpc.polkachu.com',
      'https://rpc.umee.testnet.run:443',
    ],
    chain: 'umee',
    standingFee: 0.002,
    gas: '100000',
  },
]

export const getChain = (chain: string): TChain | undefined => {
  return chains.find((item: TChain) => item.chain === chain)
}

export default chains
